name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs-release.yaml"
      - "docs/**"

jobs:
  release-docs:
    name: Release documentation
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Get GitHub API token
        id: get-app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.PHYBROS_APP_ID }}
          private_key: ${{ secrets.PHYBROS_APP_PRIVATE_KEY }}

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          token: ${{ steps.get-app-token.outputs.token }}
          fetch-depth: 0

      - name: Build docs
        uses: docker://ghcr.io/bjw-s/mdbook:0.4.28@sha256:a8a45bc791374befc91e0936c4e2cb654b8e78b2beefb3c4d061e871ab94a83c
        with:
          args: bash -c "cd docs && mdbook build"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ steps.get-app-token.outputs.token }}
          publish_dir: ./docs/book/html
          destination_dir: docs
          user_name: 'bjw-s-bot[bot]'
          user_email: 'bjw-s-bot <87358111+bjw-s-bot[bot]@users.noreply.github.com>'
