name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs-release.yaml"
      - "docs/**"

jobs:
  release-docs:
    name: Release documentation
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Get GitHub API token
        id: get-app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.PHYBROS_APP_ID }}
          private_key: ${{ secrets.PHYBROS_APP_PRIVATE_KEY }}

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          token: ${{ steps.get-app-token.outputs.token }}
          fetch-depth: 0

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          python-version: "3.10"

      - name: Install mkdocs
        shell: bash
        working-directory: src
        run: |
          pip install -r ./.ci/mkdocs/requirements.txt

      - name: Build documentation
        shell: bash
        working-directory: src
        run: |
          mkdocs build --config-file ./.ci/mkdocs/mkdocs.yaml -d "$PWD/../dest/docs"

      - name: Commit changes
        shell: bash
        working-directory: dest
        run: |
          git config user.name "phybros-bot[bot]"
          git config user.email "phybros-bot <87358111+phybros-bot[bot]@users.noreply.github.com>"
          git add docs
          git commit -m "Updated docs from ref: $GITHUB_SHA"
          git push
